apiVersion: batch/v1
kind: CronJob
metadata:
  name: finops-python-agent-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
          containers:
          - name: finops-agent
            image: finops-python-agent
            imagePullPolicy: Never
            resources:
              limits:
                cpu: "100m"
                memory: "128Mi"
              requests:
                cpu: "50m"
                memory: "64Mi"
          restartPolicy: OnFailure
          